version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_URI=redis://redis:6379

  redis:
    image: "redis:7.2.2-alpine3.18"
    ports:
      - "6379:6379"
